spring:
  datasource:
    username: nya
    password: nya777
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_docket_igor
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

pageSize: 5
formatter:
  dateTime: 'dd.MM.yyyy HH:mm'